# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "john30/ebusd:v24.1"
  amd64: "john30/ebusd:v24.1"
  armv7: "john30/ebusd:v24.1"
  i386: "john30/ebusd:v24.1"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: ebusd add-on"
  org.opencontainers.image.description: "ebusd add-on"
  org.opencontainers.image.source: "https://github.com/piotrtobolski/ha-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  BASHIO_VERSION: 0.16.2
  TEMPIO_VERSION: 2021.09.0
